# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.validator
                - tactician.middleware.locking
                - app.middleware.records_events
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler
        mutation:
            middleware:
                - tactician.middleware.validator
                - app.middleware.graphql
                - tactician.middleware.locking
                - app.middleware.records_events
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler